feat: replace deprecated deploymentconfig by deployment
BCDevOps/backup-container pull request #136
Opened 2024-09-16 14:41 UTC by RMCampos

## What
Dropped `DeploymentConfig` adding `Deployment`.

## Why
`DeploymentConfig` is now deprecated.

## References
- **Replace deprecated DeploymentConfigs with deployments:** [RedHat Learning Developers Docs](https://developers.redhat.com/learning/learn:openshift:replace-deprecated-deploymentconfigs-deployments/resource/resources:convert-deploymentconfig-deployment)

- Co-Authored by: @DerekRoberts

2024-09-16 15:09 UTC, WadeBarnes requested changes
`spec.template.spec.containers.image` should be parameterized, currently `image: ""`.

2024-10-03 13:06 UTC, RMCampos commented
> `spec.template.spec.containers.image` should be parameterized, currently `image: ""`.

@WadeBarnes 
I didn't remove the image. If you or someone else provide some guidance, I can push a commit adding the image. As you can see, there was changes regarding the image name or parameter.

2024-10-03 13:27 UTC, WadeBarnes commented
> > `spec.template.spec.containers.image` should be parameterized, currently `image: ""`.
> 
> @WadeBarnes I didn't remove the image. If you or someone else provide some guidance, I can push a commit adding the image. As you can see, there was changes regarding the image name or parameter.

@RMCampos, I know you did not change anything with respect to the code I identified.  In it's current state as a `DeploymentConfig`, it's relying on the fact that OpenShift will populate the the field with an image spec based on what's defined in the `triggers` section.  As a `Deployment` you need to explicitly define the image spec.

You'll need to change it to something like:
```
image: ${IMAGE_NAMESPACE}${SOURCE_IMAGE_NAME}:${TAG_NAME}
```

2024-10-04 02:05 UTC, DerekRoberts commented
@RMCampos Try this:
```
image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${SOURCE_IMAGE_NAME}:${TAG_NAME}"
```

It'll take another parameter for the new var:
```
parameters:
  - name: "IMAGE_REGISTRY"
    description: "Container image registry"
    value: "docker.io"
```

2024-10-04 18:54 UTC, WadeBarnes approved these changes

2024-10-04 18:54 UTC, merged

2024-10-04 18:54 UTC, WadeBarnes commented
Thanks @DerekRoberts