Reorganized file structure, updated to use KNP
BCDevOps/backup-container pull request #77
Opened 2021-03-03 22:12 UTC by esune

Adds starter KNP for enabling backup jobs.

2021-03-04 15:36 UTC, WadeBarnes requested changes
See comments

2021-03-04 15:36 UTC, WadeBarnes commented on openshift/templates/backup/backup-deploy.yaml
> +                  app: "backup-container"
Should be a parameter

2021-03-04 15:36 UTC, WadeBarnes commented on openshift/templates/backup/backup-deploy.yaml
> +                  role: "backup-container"
Should be a parameter

2021-06-02 21:19 UTC, AndrewJun97 commented
Hey @WadeBarnes , seems like the changes for the NetworkPolicies were proposed in this PR, though not merged yet.

2021-06-02 21:46 UTC, esune commented
> 
> 
> Hey @WadeBarnes , seems like the changes for the NetworkPolicies were proposed in this PR, though not merged yet.

I missed this evidently, will sync-up with @WadeBarnes  and submit an update later today or tomorrow.

2021-06-03 19:30 UTC, esune commented
@AndrewJun97 the PR has been updated, you can use the templates from my fork if you want to start working with the new templates before it is merged.

2021-06-04 13:01 UTC, WadeBarnes approved these changes

2021-06-04 13:01 UTC, merged